<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Running T-Shirt',
                'description' => 'Lightweight and breathable t-shirt, perfect for running.',
                'price' => 29.99,
                'promo_price' => 24.99,
                'in_promo' => true,
                'quantity' => 100,
                'category_id' => 1,
            ],
            [
                'name' => 'Gym Tank Top',
                'description' => 'Breathable and flexible tank top for intense gym workouts.',
                'price' => 19.99,
                'promo_price' => 14.99,
                'in_promo' => true,
                'quantity' => 200,
                'category_id' => 2,
            ],
            [
                'name' => 'Running Shoes',
                'description' => 'Lightweight shoes with excellent support for long distances.',
                'price' => 89.99,
                'promo_price' => 79.99,
                'in_promo' => true,
                'quantity' => 75,
                'category_id' => 1,
            ],
            [
                'name' => 'Training Tank Top',
                'description' => 'Breathable tank top for maximum comfort during workouts.',
                'price' => 19.99,
                'promo_price' => 14.99,
                'in_promo' => true,
                'quantity' => 150,
                'category_id' => 2,
            ],
            [
                'name' => 'Cycling Jersey',
                'description' => 'Lightweight cycling jersey with moisture-wicking technology.',
                'price' => 49.99,
                'promo_price' => 39.99,
                'in_promo' => true,
                'quantity' => 100,
                'category_id' => 3,
            ],
            [
                'name' => 'Yoga Leggings',
                'description' => 'Stretchable leggings ideal for yoga sessions.',
                'price' => 39.99,
                'promo_price' => 29.99,
                'in_promo' => true,
                'quantity' => 120,
                'category_id' => 2,
            ],
            [
                'name' => 'Soccer Cleats',
                'description' => 'High-performance cleats designed for maximum traction on the field.',
                'price' => 119.99,
                'promo_price' => 99.99,
                'in_promo' => true,
                'quantity' => 50,
                'category_id' => 4,
            ],
            [
                'name' => 'Basketball Sneakers',
                'description' => 'Comfortable and durable sneakers designed for basketball.',
                'price' => 99.99,
                'promo_price' => 79.99,
                'in_promo' => true,
                'quantity' => 80,
                'category_id' => 5,
            ],
            [
                'name' => 'Compression Shirt',
                'description' => 'Compression shirt to improve muscle performance and recovery.',
                'price' => 34.99,
                'promo_price' => 29.99,
                'in_promo' => true,
                'quantity' => 100,
                'category_id' => 2,
            ],
            [
                'name' => 'Baseball Cap',
                'description' => 'Stylish and breathable baseball cap for outdoor sports.',
                'price' => 19.99,
                'promo_price' => 15.99,
                'in_promo' => true,
                'quantity' => 200,
                'category_id' => 7,
            ],
            [
                'name' => 'Football Gloves',
                'description' => 'Grippy gloves designed for catching and protecting hands.',
                'price' => 44.99,
                'promo_price' => 34.99,
                'in_promo' => true,
                'quantity' => 90,
                'category_id' => 4,
            ],
            [
                'name' => 'Sports Sunglasses',
                'description' => 'Polarized sunglasses designed for outdoor sports.',
                'price' => 69.99,
                'promo_price' => 49.99,
                'in_promo' => true,
                'quantity' => 60,
                'category_id' => 7,
            ],
            [
                'name' => 'Track Jacket',
                'description' => 'Lightweight jacket with breathable fabric, perfect for running.',
                'price' => 79.99,
                'promo_price' => 59.99,
                'in_promo' => true,
                'quantity' => 40,
                'category_id' => 1,
            ],
            [
                'name' => 'Ski Goggles',
                'description' => 'Anti-fog ski goggles with full UV protection.',
                'price' => 89.99,
                'promo_price' => 69.99,
                'in_promo' => true,
                'quantity' => 50,
                'category_id' => 6,
            ],
            [
                'name' => 'Fitness Tracker',
                'description' => 'Smart fitness tracker with heart rate monitor and step counter.',
                'price' => 129.99,
                'promo_price' => 99.99,
                'in_promo' => true,
                'quantity' => 30,
                'category_id' => 7,
            ],
            [
                'name' => 'Gym Pants',
                'description' => 'Comfortable pants with an elastic waistband, ideal for workouts.',
                'price' => 49.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 50,
                'category_id' => 2,
            ],
            [
                'name' => 'Basketball Shorts',
                'description' => 'Lightweight and comfortable shorts, perfect for basketball.',
                'price' => 39.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 60,
                'category_id' => 5,
            ],
            [
                'name' => 'Windbreaker Jacket',
                'description' => 'Lightweight and water-resistant jacket, ideal for outdoor activities.',
                'price' => 69.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 30,
                'category_id' => 6,
            ],
            [
                'name' => 'Hiking Backpack',
                'description' => 'Durable and spacious backpack for hiking trips.',
                'price' => 89.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 40,
                'category_id' => 6,
            ],
            [
                'name' => 'Soccer Jersey',
                'description' => 'Official soccer jersey with breathable fabric for ultimate comfort.',
                'price' => 59.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 80,
                'category_id' => 4,
            ],
            [
                'name' => 'Golf Polo Shirt',
                'description' => 'Comfortable and stylish polo shirt for golfing.',
                'price' => 49.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 70,
                'category_id' => 7,
            ],
            [
                'name' => 'Swim Trunks',
                'description' => 'Quick-dry swim trunks perfect for beach and pool.',
                'price' => 29.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 150,
                'category_id' => 6,
            ],
            [
                'name' => 'Tennis Racket',
                'description' => 'High-quality tennis racket for advanced players.',
                'price' => 199.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 30,
                'category_id' => 6,
            ],
            [
                'name' => 'Ski Jacket',
                'description' => 'Insulated and waterproof jacket for skiing and snowboarding.',
                'price' => 149.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 20,
                'category_id' => 6,
            ],
            [
                'name' => 'Running Hat',
                'description' => 'Lightweight hat with moisture-wicking technology for runners.',
                'price' => 24.99,
                'promo_price' => null,
                'in_promo' => false,
                'quantity' => 90,
                'category_id' => 1,
            ],
        ];

        DB::table('products')->insert($products);
    }
}
